config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index
        @flats = Flat.all
    end

    def show
        @flat = Flat.find(params[:id])
    end

    def new
        @flat = Flat.new
    end

    def create
        @flat = Flat.new(flat_params)
        if @flat.save
          redirect_to flat_path(@flat)
        else
          render :new
        end
    end

    private

    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests, collection: (1..100) %>
  <%= f.submit "Add Flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/index.html.erb
<div class="container">
<h1>Flats</h1>
<% @flats.each do |flat| %>
<ul>
<li><%= link_to flat.name, flat %></li>
<li><%= flat.address %></li>
<li><%= flat.description %></li>
<li><%= flat.price_per_night %></li>
<li><%= flat.number_of_guests %></li>
</ul>
<% end %>
</div>

<%= link_to 'Add New Flat', new_flat_path, class: 'btn btn-primary' %>

app/views/flats/new.html.erb
<div class="row justify-content-center">
  <div class="flat-form">
  <h1>Add a new flat</h1>
  <%= render 'form', flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<h2>Flat</h2>
<ul>
<li><%= @flat.name %></li>
<li><%= @flat.address %></li>
<li><%= @flat.description %></li>
<li><%= @flat.price_per_night %></li>
<li><%= @flat.number_of_guests %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>